[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 9600
upload_speed = 115200
; Zwiększony rozmiar bufora TX dla seriala zeby nie gubil znakow (domyslnie 256)
build_flags = -D SERIAL_TX_BUFFER_SIZE=512
